calendar:
  source: "fred"          # "fred" or "trading_econ"
  mode: "day"             # "day" or "approx_time"
  approx_times_utc:       # used only if mode == "approx_time"
    Consumer Price Index: "13:30"
    Employment Situation: "13:30"
    Gross Domestic Product: "12:30"
    Personal Income and Outlays: "12:30"
  fred_release_names:
    - "Consumer Price Index"
    - "Employment Situation"
    - "Gross Domestic Product"
    - "Personal Income and Outlays"
  gdelt_event_keywords:
    - "CPI"
    - "inflation"
    - "payrolls"
    - "Nonfarm Payrolls"
    - "FOMC"
    - "rate decision"
    - "ECB"
    - "CPI euro area"
