symbols:
  fx:
    - "EURUSD"
    - "GBPUSD"
    - "USDJPY"

date_range:
  start: "2019-01-01"
  end: "2024-12-31"

sources:
  alpha_vantage: true
  twelvedata: true
  gdelt: true
  tradingeconomics: true
  fred: true
  wikipedia: true

landing_path: "landing"
delta_path: "delta"
